{
  "uid" : "b81760f560170512",
  "name" : "simpleFailingTest",
  "fullName" : "test.java.tests.DummyTest.simpleFailingTest",
  "historyId" : "795ab4f489130ed320b22e2b8dbdd57b",
  "time" : {
    "start" : 1605988938529,
    "stop" : 1605988938649,
    "duration" : 120
  },
  "status" : "failed",
  "statusMessage" : "expected [www.google.com] but found [https://www.amazon.com/]",
  "statusTrace" : "java.lang.AssertionError: expected [www.google.com] but found [https://www.amazon.com/]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:575)\r\n\tat org.testng.Assert.assertEquals(Assert.java:585)\r\n\tat test.java.tests.DummyTest.simpleFailingTest(DummyTest.java:23)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\r\n\tat java.base/java.lang.Thread.run(Thread.java:832)\r\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "setUp",
    "time" : {
      "start" : 1605988932027,
      "stop" : 1605988938521,
      "duration" : 6494
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "afterStages" : [ {
    "name" : "tearDown",
    "time" : {
      "start" : 1605988939250,
      "stop" : 1605988939930,
      "duration" : 680
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "labels" : [ {
    "name" : "package",
    "value" : "test.java.tests.DummyTest"
  }, {
    "name" : "testClass",
    "value" : "test.java.tests.DummyTest"
  }, {
    "name" : "testMethod",
    "value" : "simpleFailingTest"
  }, {
    "name" : "parentSuite",
    "value" : "Lesson11"
  }, {
    "name" : "suite",
    "value" : "Failing dummy tests"
  }, {
    "name" : "subSuite",
    "value" : "test.java.tests.DummyTest"
  }, {
    "name" : "host",
    "value" : "XPS7"
  }, {
    "name" : "thread",
    "value" : "32076@XPS7.TestNG-test=Failing dummy tests-1(17)"
  }, {
    "name" : "framework",
    "value" : "testng"
  }, {
    "name" : "language",
    "value" : "java"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "b81760f560170512.json",
  "parameterValues" : [ ]
}